<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../client-app/Services/GradeComparisonService.cs" Link="GradeComparisonService.cs" />
    <Compile Include="../../client-app/Services/GradeAcademicPeriod.cs" Link="GradeAcademicPeriod.cs" />
    <Compile Include="../../client-app/Models/AcademicRecord.cs" Link="AcademicRecord.cs" />
  </ItemGroup>
</Project>
